### ISSUE TITLE
Memory Leak via Module.children

### ISSUE THREAD

**Issue by Flarna** [analog-nico/stealthy-require#2]
I think there is a potential memory leak if stealthy-require is used.

If a non internal module is required `Module._load()` creates a new Module instance.
The constructor of Module appends this new instance to the parent Module which is the Module where the stealthy require is done and therefore not effected by the post load require cache clean.

Therefore even the stealthy required module instance is removed from require cache there are leftovers in the parent Module.

**Comment by analog-nico** [comment]
Mmh, you seem to have a point. However, I can't quite wrap my head around it.

Do you mean this?

```
Module A
\-> Module B (non-internal, stealthy-required)
```

Thus:

``` js
A.children.includes(B) // -> true, always
require.cache.includes(B) // -> true at first, false after the cache clean-up of stealthy-require
```

Where do you see a memory leak? Because `A.children.includes(B)` is still `true` maybe?

**Comment by Flarna** [comment]
Try following script and watch the memory consumption:

```
var stealthyRequire = require("stealthy-require");
function doSome() {
    for (var i = 0; i < 5000; i++) {
        stealthyRequire(require.cache, function () {
            return require('./dummy');
        });
    }
    setTimeout(doSome, 2000);
}
doSome();
```

dummy.js is just an empty file in the same folder - or some other real JS file (no internal module!).

Assume above script is named app.js; then the Module with key `<fullpath>/app.js` is the parent which gets a new child with key `<fullpath>/dummy.js` on every iteration.

Strictly speaking this is no memory leak as app.js has really a _lot_ children (even all of them are clones ...), but I don't think that this is intended here.

In case a stealthyRequire is just done once or a few times it's most likely no issue, but if someone does this per request its quite bad.

**Comment by novemberborn** [comment]
> In case a stealthyRequire is just done once or a few times it's most likely no issue, but if someone does this per request its quite bad.

😊 

I can confirm that `module.children.length` increases on every request. Perhaps `module` should _also_ be passed to `stealthyRequire()`. After loading it can trim the `children` array to its pre-loading length.

**Comment by analog-nico** [comment]
Thanks for putting a finger on it @novemberborn !

**Comment by analog-nico** [comment]
Hey guys, I decided to provide a fix for that by letting the user truncate the `module.children` array. It’s now [documented in the README](https://github.com/analog-nico/stealthy-require#preventing-a-memory-leak-when-repeatedly-requiring-fresh-module-instances-in-nodejs).

I didn’t choose to include the fix in `stealthy-require` – by passing `module` like @novemberborn suggests – because it only affects node.js and not Browserify and Webpack and also is only relevant for the use case in which the same module is required repeatedly.

I hope this helps.
