### ISSUE TITLE
module undefined in require.cache when it's kept.

### ISSUE THREAD

**Issue by jasperjn** [analog-nico/stealthy-require#4]
Hi
My project launched failed after request-promise update to v4.2.1. The error message indicates that require.cache got undefined with several keys when I try to iterate objects in `requird.cache`.
References:
https://github.com/request/request-promise/commit/fdc522a5f0ec44e00a9d34041831c5953d66e58d
Because `tough-cookie` has not been required, tough-cookie does not exist in `originalCache`. It'll assign undefined with keys in the `modulesToKeep` on the next line.
https://github.com/analog-nico/stealthy-require/blob/master/lib/index.js#L71

Example
```
var webpack = require('webpack');
var stealthyRequire = require('./index');

var newWebpack = stealthyRequire(require.cache, function () {
    return require('webpack');
}, function () {
    require('tough-cookie');
}, module);

Object.keys(require.cache).forEach(key => {
    if (!require.cache[key]) {
        // tough-cookies and it's dependencies undefined. But key is still there.
    }
});
```

**Comment by analog-nico** [comment]
Thanks for the detailed analysis @jasperjn !

One `if` is missing:
``` diff
        for ( var k = 0; k < modulesToKeep.length; k+=1 ) {
+           if (stealthCache[modulesToKeep[k]]) {
                requireCache[modulesToKeep[k]] = stealthCache[modulesToKeep[k]];
+           }
        }
```

I am on it!

**Comment by analog-nico** [comment]
I just published `stealthy-require@1.1.1`. Since `request-promise` uses `^1.1.0` the new version will get installed if you run `npm update`.

Could you do me a favor and see if your app works with the new `stealthy-require` version? I implemented a test case for this issue but better be safe than sorry. Thanks!

**Comment by jasperjn** [comment]
@analog-nico It works! Thank you.

**Comment by analog-nico** [comment]
Alright. Thanks again for reporting this @jasperjn !
